In [1]:
import numpy as np

In [2]:
escalar = 5.678
vector = np.array([3,4,5,6])
matriz = np.array([[1,2],[3,4],[5,6]])
tensor = np.array([
    [[1,2,3,30],[4,5,6,11],[7,8,9,12]],
    [[11,12,13,33],[14,15,16,34],[17,18,19,35]],
    [[21,22,23,36],[24,25,26,37],[27,28,29,38]],
])

In [3]:
escalar_t = escalar.T

AttributeError: 'float' object has no attribute 'T'

In [4]:
vector_t = vector.T
print(vector_t)

[3 4 5 6]


In [5]:
matriz_t = matriz.T
print(matriz_t)

[[1 3 5]
 [2 4 6]]


In [6]:
matriz_t.shape

(2, 3)

In [7]:
matriz.shape

(3, 2)

In [8]:
tensor_t = tensor.T
print(tensor_t)

[[[ 1 11 21]
  [ 4 14 24]
  [ 7 17 27]]

 [[ 2 12 22]
  [ 5 15 25]
  [ 8 18 28]]

 [[ 3 13 23]
  [ 6 16 26]
  [ 9 19 29]]

 [[30 33 36]
  [11 34 37]
  [12 35 38]]]


In [9]:
print(tensor)

[[[ 1  2  3 30]
  [ 4  5  6 11]
  [ 7  8  9 12]]

 [[11 12 13 33]
  [14 15 16 34]
  [17 18 19 35]]

 [[21 22 23 36]
  [24 25 26 37]
  [27 28 29 38]]]


In [11]:
A = matriz
B = matriz_t

In [12]:
C = A+B

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [13]:
A = np.array([[1,2],[3,4],[5,6]])
B = np.array([[6,5],[4,1],[2,1]])
C = A+B
print(C)

[[7 7]
 [7 5]
 [7 7]]


In [14]:
D = matriz + escalar
print(D)

[[ 6.678  7.678]
 [ 8.678  9.678]
 [10.678 11.678]]
