In [1]:
import numpy as np

In [4]:
A = np.array([[2,3],[5,7],[11,13]])
B = np.array([[1,3],[2,1]])
C = np.array([[3,1],[4,2]])

In [5]:
# Asociativa
ABC = A.dot(B.dot(C))
ABC

array([[ 60,  26],
       [145,  63],
       [295, 129]])

In [6]:
AB_C = A.dot(B).dot(C)
print(AB_C)

[[ 60  26]
 [145  63]
 [295 129]]


In [8]:
# distributiva
D = A.dot(B+C)
E = (A.dot(B))+(A.dot(C))

In [11]:
print(D,E,sep='\n\n')

[[ 26  17]
 [ 62  41]
 [122  83]]

[[ 26  17]
 [ 62  41]
 [122  83]]


In [12]:
print(D==E)

[[ True  True]
 [ True  True]
 [ True  True]]


In [13]:
F = B.dot(C)

In [14]:
G = C.dot(B)

In [15]:
print(F==G)

[[False False]
 [False False]]


In [16]:
print(F,G,sep='\n\n')

[[15  7]
 [10  4]]

[[ 5 10]
 [ 8 14]]


In [17]:
v1 = np.array([[2],[7]])
v2 = np.array([[3],[5]])

In [18]:
v1_tv2 = v1.T.dot(v2)
v2_tv2 = v2.T.dot(v1)

In [19]:
print(v1_tv2,v2_tv2,sep='\n\n')

[[41]]

[[41]]
