In [1]:
import numpy as np

In [2]:
A = np.array([[2,3],[5,7],[11,13]])
B = np.array([[1,3],[2,1]])

In [3]:
print(A)

[[ 2  3]
 [ 5  7]
 [11 13]]


In [4]:
B

array([[1, 3],
       [2, 1]])

In [5]:
AB_t = A.dot(B).T

In [6]:
B_tA_T = B.T.dot(A.T)

In [7]:
AB_t == B_tA_T

array([[ True,  True,  True],
       [ True,  True,  True]])

In [8]:
AB_t

array([[ 8, 19, 37],
       [ 9, 22, 46]])

In [9]:
B_tA_T

array([[ 8, 19, 37],
       [ 9, 22, 46]])

In [11]:
np.random.randint(2,13,(3,2))

array([[10,  2],
       [ 4, 11],
       [10,  2]])