In [1]:
import numpy as np

In [2]:
identidad = np.eye(4)
identidad

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [3]:
vector = np.array([[2],[3],[5],[7]])

In [4]:
identidad.dot(vector)

array([[2.],
       [3.],
       [5.],
       [7.]])

In [5]:
A = np.array([[1,0,1],[0,1,1],[-1,1,1]])
A

array([[ 1,  0,  1],
       [ 0,  1,  1],
       [-1,  1,  1]])

In [6]:
inversa_A = np.linalg.inv(A)
inversa_A

array([[ 0.,  1., -1.],
       [-1.,  2., -1.],
       [ 1., -1.,  1.]])

In [7]:
A.dot(inversa_A)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
singular = np.array([[1,1],[1,1]])
singular

array([[1, 1],
       [1, 1]])

In [9]:
np.linalg.inv(singular)

LinAlgError: Singular matrix