In [1]:
import numpy as np

In [2]:
np.set_printoptions(suppress=True)

In [3]:
A = np.array([[3,1],[2,1]])
A

array([[3, 1],
       [2, 1]])

In [6]:
b = np.array([[1],[1]])

In [5]:
inversa_A = np.linalg.inv(A)
inversa_A

array([[ 1., -1.],
       [-2.,  3.]])

In [8]:
x = inversa_A.dot(b)
x

array([[0.],
       [1.]])

In [13]:
A.dot(x)

array([[1.],
       [1.]])

3x + y = 3

2x + y = 7

In [11]:
sol_2 = inversa_A.dot(np.array([[3],[7]]))
sol_2

array([[-4.],
       [15.]])

In [12]:
A.dot(sol_2)

array([[3.],
       [7.]])