In [1]:
import numpy as np

In [2]:
vector = np.array([1,2,3,4,5])
matriz = np.diag(vector)

matriz

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [3]:
matriz[0:4,0:3]

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3],
       [0, 0, 0]])

In [4]:
matriz[0:3,0:4]

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0]])

In [5]:
A = np.diag([2,3,4,5])
A

array([[2, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 5]])

In [6]:
v1 = np.array([[1,1,1,1]])
A.dot(v1.T)

array([[2],
       [3],
       [4],
       [5]])

In [10]:
A_inv = np.diag([1/2,1/3,1/4,1/5])
A_inv

array([[0.5       , 0.        , 0.        , 0.        ],
       [0.        , 0.33333333, 0.        , 0.        ],
       [0.        , 0.        , 0.25      , 0.        ],
       [0.        , 0.        , 0.        , 0.2       ]])

In [11]:
identidad = A.dot(A_inv)
identidad

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
A_inv_calc = np.linalg.inv(A)
A_inv_calc

array([[0.5       , 0.        , 0.        , 0.        ],
       [0.        , 0.33333333, 0.        , 0.        ],
       [0.        , 0.        , 0.25      , 0.        ],
       [0.        , 0.        , 0.        , 0.2       ]])

In [14]:
A.T

array([[2, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 5]])

In [15]:
A

array([[2, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 5]])

In [16]:
simetrica = np.array([[1,2,3],
                     [2,-1,7],
                     [3,7,11]])
simetrica

array([[ 1,  2,  3],
       [ 2, -1,  7],
       [ 3,  7, 11]])

In [17]:
simetrica.T

array([[ 1,  2,  3],
       [ 2, -1,  7],
       [ 3,  7, 11]])