In [1]:
import numpy as np

$$A^tA = AA^t = Id$$

In [2]:
matriz = np.array([[1,0,0],
                  [0,1,0],
                  [0,0,1],
                  ])

matriz

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [3]:
matriz[:,0].dot(matriz[:,1])

0

In [6]:
matriz[:,0].dot(matriz[:,2])

0

In [7]:
matriz[:,1].dot(matriz[:,2])

0

In [8]:
print(np.linalg.norm(matriz[:,0]))
print(np.linalg.norm(matriz[:,1]))
print(np.linalg.norm(matriz[:,2]))

1.0
1.0
1.0


In [9]:
print(matriz[0,:].dot(matriz[1,:]))
print(matriz[0,:].dot(matriz[2,:]))
print(matriz[1,:].dot(matriz[2,:]))

0
0
0


In [10]:
print(np.linalg.norm(matriz[0,:]))
print(np.linalg.norm(matriz[1,:]))
print(np.linalg.norm(matriz[2,:]))

1.0
1.0
1.0


In [11]:
A = np.array([[np.cos(100), -np.sin(100)],
              [np.sin(100), np.cos(100)],
             ])
A

array([[ 0.86231887,  0.50636564],
       [-0.50636564,  0.86231887]])

In [13]:
print(np.linalg.norm(A[0,:]))
print(np.linalg.norm(A[1,:]))
print(np.linalg.norm(A[:,0]))
print(np.linalg.norm(A[:,1]))

0.9999999999999999
0.9999999999999999
0.9999999999999999
0.9999999999999999


In [14]:
print(A[0,:].dot(A[1,:]))
print(A[:,0].dot(A[:,1]))

0.0
0.0


In [15]:
A_t = A.T
print(A_t.dot(A))
print(A.dot(A_t))

[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]


In [16]:
A_inv = np.linalg.inv(A)
A_inv

array([[ 0.86231887, -0.50636564],
       [ 0.50636564,  0.86231887]])

$$A^t=A^{-1}$$

In [17]:
A_t

array([[ 0.86231887, -0.50636564],
       [ 0.50636564,  0.86231887]])

In [19]:
1/A_t.dot(A)

C:\Users\VALENCIA\.conda\envs\Platzi-FundamentosAL\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[ 1., inf],
       [inf,  1.]])